name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Push to Releases
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
